### PR TITLE
Add ability to toggle developer tools

### PR DESCRIPTION
**Pull request by bshackelford**
👋🏻 Hello, I've been using this recently and it's really great. Thank you for creating it. I would love to help and figured to make it easier for development I'd make the developer tools a little more accessible while iterating locally. Also did some clean up while I was in there.

## Summary

- **Adds ability to toggle developer tools when developing**
- Fix ESLint warnings
- Ensure minimum Node version of `v12`
- Remove unused `proptypes` package
- Add `TODO` to implement `changeResult` for Salmon Run graph

### CODE REVIEW

**Comment by bshackelford** [comment]
@hymm Can't seem to add you as a reviewer so tagging you here. Let me know how I can help.

**Comment by hymm** [comment]
Thanks for the reminder.  I'll try to get to this soonish.  Hopefully will remember to after work today.

**Comment by hymm** [comment]
Looks good.  Thanks for the contribution.

If you're interested in working on the Salmon Run stuff feel free.  I haven't really played salmon run in 2 years and so don't have a ton of motivation to work on it.

**Comment by bshackelford** [comment]
Cool. Thanks @hymm. I don't play much either 😅 but I can take a stab. 👍🏻

**Pull request merged**
