### PR TITLE
Add ability to select start of week for league stats, to allow for qu…

### PR DESCRIPTION
**Pull request by okuRaku**
This lets you pick the start of week, either for your preference or for doing analysis just on the last few days (for example after patch 1.3.0).   Still not super precise, but still prevents someone from doing too crazy of an API volley.

image

### CODE REVIEW

**Comment by hymm** [comment]
image

tried to use Sunday just a little after midnight on Sunday and things look a little bugged.

**Comment by hymm** [comment]
my one comment would be to put a little css padding on **Start of Week**.

**Comment by okuRaku** [comment]
Darn, I've avoided learning how the css interaction works up to this point :)

Yeah, I encountered that after midnight too when picking the same day.   It happens, I think, when there's no league data for that day (or that 'week' of 1 day).    I'll see if I can make it fail more appropriately.   Maybe if there's no data for a day yet, I'll just assume you meant the same day of week but one week ago.

**Comment by okuRaku** [comment]
Fixed the bug, added padding, and went ahead and added a feature of showing the date range to help keep it as clear as possible what data is being shown.

**Comment by hymm** [comment]
looks good.  I'll go ahead and merge it

**Pull request merged**
