### PR TITLE
League Meta Tab

### PR DESCRIPTION
**Pull request by okuRaku**
Still learning how to navigate github, I only expected to see my commits in the history.

Also, a lot of the 'changes' were due to pre-commit prettify, can try to undo if needed (I assumed this was due to the project's config but maybe not).

Notes for the feature:
In current stage, a few things are definitely lacking:  
* did not intl-ize yet
* sorting is broken, tried to follow the pattern but the way I set up the dimensions I couldn't make it work yet
* I'd really like to see green/red highlighting on the change by week, but need guidance on a good way to do that with React.
* I added a new getApiAsync feature because querying for league data hits holes (when there was maintenance, no reports yet, etc).   In general, the hits to the league api are probably a little too aggressive (luckily the memoize provides caching after the first time, if I understand correctly)

image

### CODE REVIEW

**Comment by hymm** [comment]
on the merge, we'll do a squash and merge.  So it'll only show up as 1 commit.

switch the merge target to the v0.3.0_beta branch.  

I'll run prettier by hand on that branch and hopefully it'll fix some of the diff problems

**Comment by hymm** [comment]
oh, wait.  you should rebase onto v0.3.0_beta

**Comment by okuRaku** [comment]
ahhh I tried to do it quickly but my rebase didn't work correctly (some reason all the import statements got missed).  I've run out of time right now so I'll try to clean it up later today.  Thx!

**Comment by hymm** [comment]
sounds good.  Let me know if you need any help.

**Pull request closed without merging**
