### PR TITLE
add checkbox to combine hero replica league stats with regular

### PR DESCRIPTION
**Pull request by okuRaku**

### CODE REVIEW

**Comment by hymm** [comment]
could you add this as a saved setting to userData?

you'd make calls to `setToStore` and `getFromStore`, similar to what was done [here](https://github.com/konamugi/squid-tracks/commit/b46019b2b78af706dd9e28f6eab14d6881994150#diff-43d6bd0c5e0f9bc940befa68ab214b4dR62)
in settings.js

**Comment by hymm** [comment]
you'll also need to add a default setting in public/main/index.js

**Comment by okuRaku** [comment]
Done!

**Comment by hymm** [comment]
merged.  Thanks!

**Pull request merged**
