### PR TITLE
add ja messages

### PR DESCRIPTION
**Pull request by okuRaku**
Wrote these up real quick if you wanted them.   I'm fluent in Japanese and used stat.ink + the Japanese version of the splatnet app to try and make all the terms match what Japanese players will expect.   Definitely open to corrections if someone has them though!

### CODE REVIEW

**Comment by hymm** [comment]
I think there are some strings missing from the ja.json file.  Could you run these commands on your branch and do those translations too?
```js
// update some files in build.
yarn run dev 
// quit squid tracks and run
yarn run manage:translations
// this should add a bunch of keys to ja_json file
```

**Comment by okuRaku** [comment]
Sure will do!  I bet there are yeah, for one I noticed store was missing (and I added it manually).   Cool there's a way to auto populate it!

**Comment by okuRaku** [comment]
Done!

**Comment by hymm** [comment]
nice.  how confident are you in the translations?  should we find someone to double check it before merging?

**Comment by okuRaku** [comment]
Very confident!  I've studied Japanese for about 14 years.   The corrections may be game specific terms (didn't play S1 in Japanese, but picked up a lot already).   It's 100% understandable as it is, but I'm sure when we get a few more native speakers using it regularly they'll have some improvements we can make for polish, which would be great.

**Comment by hymm** [comment]
Looks good.  I'm going to squash and merge it.

If you do anymore work, you should start a new branch.  Squash and merge makes it a pain to keep working on the same branch as I had the pain of finding out recently.  You lose info so commits that are part of the squash are seen as diffs later.

**Pull request merged**
