### PR TITLE
Fixing kill avg display + adding pictures to schedule and imitate app style for maps in schedule

### PR DESCRIPTION
**Pull request by DanSyor**

### CODE REVIEW

**Comment by hymm** [comment]
* [ ] rebase onto master
* [ ] add yourself to the authors in the README
* [ ] switch to using react-bootstrap?

Couple things first.  In the future rename your branch to something other than master, I had to wipe out my master branch to review.  Not a big deal since I'm not working on the program right now, but could be a little annoying in the future. Also before I'll accept this PR please rebase it onto my master branch.  This is for cleanliness of the git history.

There is one major change I'd make.  I want to change the divs and img tags to using react-bootstrap.  This allows the images to be responsive and resize for different screen sizes.  I can accept the pull request as is and fix it myself, but if you'd like to do it here are some instructions:

To do this I would replace the divs with Grid, Row, Col.  If you play with resizing the window, notice that on smaller screen sizes the schedule page is 3 columns, but at smaller sizes it's just 1 column. In the Col element you specify the column width in different screen sizes with xs, sm, md, lg.  The full width of the container is 12 units.  So if you want something to take up half the width, you would use 6.  I'd try and do 2 images on a row at large screen sizes and 1 on smaller screen sizes.  You might need to play with this a bit to see what works.

For the img tag you could switch to the Image and make your own container or try to use Thumbnail.  I'm not sure what would be easier.  Feel free to override the css styling to get the look you want with margins, padding, rounded corners, ect.  You may have to use chrome dev tools to see the classes you want.

See documentation here
https://react-bootstrap.github.io/components.html#thumbnail

Feel free to ping me or write here if you have questions.

**Comment by hymm** [comment]
I see you merged with master.  That's fine for now.  But in the future do a rebase instead.  It leaves a cleaner git history.

**Comment by DanSyor** [comment]
Noted.
Due to the css md col class overwriting padding, I put the div's within Col's instead of their content.
I've moved the position of the mode name and made it <strong>. Uncertain if mode text should be centered (and if auto margin of the divs should be readded).
(also I'm not that confident on my use of Col's, so maybe you'll want to "redo" the whole thing anyway)
Using responsive pictures + col's seems to make pictures appear pretty small, the minimum width I set was the maximum one to allow two pictures (per play category) on a single line with the default window size...
I didn't really know what to put next to my name in the Authors section of the readme so I put something that may be about right for now...
I'll be away part of this week-end so feel free to do any correction you see fit.

**Comment by hymm** [comment]
looks good, I'll probably try and adjust the margins a bit, but I'll go ahead and merge it.  Another change I'd like to make in the future is to use the short names from stat.ink when the images get too small.  So the text doesn't overflow onto two lines

**Pull request merged**
