### PR TITLE
League Stats Tab

### PR DESCRIPTION
**Pull request by okuRaku**
Still learning how to navigate github, I only expected to see my commits in the history.

Also, a lot of the 'changes' were due to pre-commit prettify, can try to undo if needed (I assumed this was due to the project's config but maybe not).

Notes for the feature:
In current stage, a few things are definitely lacking:  
* did not intl-ize yet

* I added a new getApiAsync feature because querying for league data hits holes (when there was maintenance, no reports yet, etc).   In general, the hits to the league api are probably a little too aggressive (luckily the memoize provides caching after the first time, if I understand correctly)

image

### CODE REVIEW

**Comment by okuRaku** [comment]
bleh there's a bug in my date algo, let me try to fix

**Comment by hymm** [comment]
is this ready for review?

**Comment by okuRaku** [comment]
Sure.  Sorting still doesn't work and I'd really like colors on some of the numbers but it should be useable as it is now!

**Comment by hymm** [comment]
could you rename the branch.  It's sort of awkward for me to checkout

**Comment by hymm** [comment]
* [ ] Seems like when changing teams-pairs, and region.  You need to hit the reload button.  I would pull those buttons up to where the load data button is.
* [ ] once you do this I would add `bsStyle="primary"` to the load data button
* [ ] also add some status to the panel header.  So it'd say Japan Teams League Weapon Stats
* [ ] should fix sorting.  the sort column needs to be something like 'uses.last_week`.  You'll probably need to change this dynamically when the buttons are pressed.
* [ ] not sure about the diff value.  As it is it's a bit confusing.  Maybe if separated it from the parenthesis it would work better.  Different column or square brackets?  Also what is it being diffed with.  Is this week being diffed with last week or last last week?
* [ ] you're writing to the state in meta.js and it's causing an eslint error. should be calling `setState` there.  If you need to use immutability-helper.  It's added in the annie branch which I will be merging shortly.

let me know if you have any questions.

**Comment by hymm** [comment]
it might be better to remove last last week and allow the use to pick this week from a drop down or start day from a calendar.

**Comment by okuRaku** [comment]
The diff is from the previous week (column to the left).   Maybe square brackets would help, but I was thinking it for sure needs +'s for positive increases and even better would be green/red, but I couldn't get this coded in (not familiar enough with React to do more than a single line in the 'html' part).

I had thought about having arbitrary dates but when considering how I would actually use the data, it was to look at the trends and that is better accomplished by looking at fixed windows (so I settled on two weeks prior plus the current, which shows you how this week is or is not fitting the expectation).   There's a risk with opening up the window that they overload the API (I'm not sure where this is, but at least with this implementation the most they ever hit is 3 full weeks).   

All to say, I think having arbitrary date selections / comparisons is better held off until we have the data better cached for new/returning users.   But certainly if you or someone wants to go ahead and implement that as you described, I don't mind.   I put this code up for you to use as-is or modify however you like really.

On sorting, yeah I know conceptually how it needs to work but again, couldn't get the code working in the time I had.   The way it should work is it should resort either when clicking "Two Weeks Ago", "Last Week"  or "This Week" by whichever stat is currently displayed, and then again if you change the stat displayed, should sort again on whichever column you had last selected.

**Comment by okuRaku** [comment]
@hymm incorporated all of your feedback / fixes.  So glad I got sorting working, was easier once I fully understood your sort function better (using '.' as a child key).

I need help making the diff from previous week make more sense, how would I color that?

What I want to do is add logic in the 'html' part but I know that's not the right way to do it / couldn't make that work.   I'd like to see how it looks even putting the -/+ in a bsStyle danger/success box but I couldn't figure out how to do that.  Maybe I need to define a new component?

**Comment by hymm** [comment]
for color I would do something like
```js
// in the render function
<span style={{ color: value >= 0 ? 'green' : 'red' }}>{value}</span>
```

**Comment by hymm** [comment]
After using it some more I see why you have last last week.  Didn't realize that this week was a running total.  It makes complete sense to show 2 full weeks.

Couple last corrections
* [ ] title of panel shouldn't change before hitting the load button, or content of panel should be emptied, when changing region and team type.
* [ ] add the team type and region as a third parameter of event.  So it'd look something like `event('league_dict', 'refresh', 'pair-jp')`

I also added an issue about caching #65.  I'm going to add it in for battles, because I need it to implement exporting to a csv file, which SplatStats is asking for.  Hopefully I'll have that in by Friday.

Are you comfortable with how hard the league page is hitting splatnet or do you think we should implement caching before including this in the full release?

**Comment by okuRaku** [comment]
Thanks for those last corrections, will work on those when I have time next.

Regarding the api hits, the caching provided by promise-memoize is helping a lot, and is definitely working (I tested by pulling my network plug, could still use the tab for stuff I'd already hit).   I've been hitting it pretty hard and have not had an issue yet, so I think it's safe to release (without a date picker), but of course impossible to be sure.   It's just definitely wasteful, as my query for, say, 2017082212T is going to be identical to the next user's, so as soon as we have that data centralized we should definitely switch this to use it.

At the start, I thought about having a utility to load a bunch of that data into a json file / local 'db' in a quick and dirty manner and then have that in the project (maybe updating it once a month or something), but when I saw how memoize was caching, I thought that was 'good enough' until there's a proper data source; if you're using it every day, you're only doing 12 or so new hits.   

Maybe one of us could set up a dummy nintendo account and see if we can get it to break after a point...

**Comment by okuRaku** [comment]
Finished!  By the way, I tried creating a dummy account but I think it needs to actually have used the splatnet app for it to work, even in SquidTracks, was getting:
`[1] [21:43:04:0916] [error] Unhandled Promise Rejection in Main: TypeError: Cannot read property 'webApiServerCredential' of undefined`

So, for science, I went back to my account and hit all the combinations.   Seems no damage so far 👌 .

**Comment by hymm** [comment]
lol.  I'm too scared to try something like that.  Though I've probably hit my account pretty hard when I was testing some stuff.

I think you need to have played Splatoon to get access.  I remember I wasn't able to get in when the app came out early.

**Comment by hymm** [comment]
I'll review the changes tomorrow and probably merge it if I don't see any problems.

**Comment by hymm** [comment]
couple things I noticed
* [ ] when there's missing data it's putting 404 errors into the log.  We should probably suppress these when retrieving logging data.
* [ ] not sure I like `Load Data Above` maybe `Select Data Above`?

**Comment by okuRaku** [comment]
Done 🆗

**Comment by hymm** [comment]
looks good going to merge it

**Pull request merged**
